config/routes.rb
Rails.application.routes.draw do
  get 'learn/new'
  get 'learn/show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  get '/dashboard',to: 'static_pages#index'
  
  get '/members',to: 'users#index'
  get '/profile' ,to: 'users#show'
  get '/signup',to: 'users#new'
  get '/setting', to: 'users#setting'

  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :categories
  resources :words
  resources :learns , only: [:new, :create, :show]

  get '/categories/:category_id/words/new', to: 'words#new', :as => :new_category_words

  get '/categories/:category_id/words', to: 'words#index', :as => :category_words_list

  get '/categories/words', to: 'categories#show', :as => :category_words

  get '/categories/:category_id/words/:word_id/edit', to: 'words#edit', :as => :edit_category_words

  get '/categories/:category_id/words/', to: 'words#index', :as => :words_path
  
  resources :users do
    member do
       get :following, :followers
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord 
  has_many :words, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action:admin_user, only: [:new, :create, :show]

  def index
   @categories = Category.all
  end

  def edit
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
    flash[:success] = "Saved successfully"
    redirect_to categories_path
    else 
      flash[:danger] = "Invaild content. Try again"
      render 'new'
  end
end

def show
  @categories = Category.all
end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Saved succesfully!"
      redirect_to categories_path
    else
      flash[:danger] = "Invalid content. Try again"
      render 'edit'
    end
  end

  def destroy
      Category.find(params[id]).destroy
      flash[:success] = "Category deleted"
      redirect_to categories_path
  end


 private
  def  category_params
     params.require(:category).permit(:title, :description)
   end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, "Category_edit") %>
<br>
<div class="container">
    <div class="form">
        <h1 class="text-center">Edit category</h1>
        <div class="row"> 
            <div class="column is-5 w-50">
                <%= form_for @category do |f| %>
                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title , autofocus: true, autocomplete: "title", class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= f.label :description ,"Description" %>
                        <%= f.text_field :description ,class:"form-control" %>
                    </div>
                    <br>
                    <div class="form-group">
                        <%= f.submit "Submit",class:"btn btn-block btn-success" %>
                    </div>
                <br>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<% provide(:title,'Profile') %> 
<br> 
    <div class="container">
        <ul class="nav nav-pills nav-warning float-right justify-content-end">
            <li class="nav-item">
                <a class="nav-link active" href="/categories">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/categories?learned=1">Learned</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/categories?learned=0">Not learned</a>
            </li>
        </ul>
        <h1>Categories (<%= @categories.count %>)</h1>

        <div>
            <ul class=" row mt-4">
            <% @categories.each do |category|%>
                <div class="border rounded-lg m-2 w-50 col-xs-5 col-lg-5">
                    
                    <li class="flex-row">
                        
                        <h3><%= category.title %></h3>
                    </li>
                    <li>
                        <%= category.description %>
                    </li>
                    <li>
                    <% if current_user.admin == true %>   
                    <%= link_to "Edit", edit_category_url(category), class:"btn btn-large btn-success"  %>

                    <%= link_to "Delete", category_url(category), method: :delete, data: {confirm: "are you sure? "}, class:"btn btn-large btn-danger"  %>

                    <% end %>
                    <%= link_to "Learn", " " ,class: "btn btn-large btn-info w-100 h-5 mt-1" %>
                    </li>
                </div>
                <% end %>
            </ul>  
        </div>
    </div>

app/views/categories/new.html.erb
<% provide(:title, "Category_new") %>
<br>
<div class="container">
    <div class="form">
        <h1 class="text-center">Add category</h1>
        <div class="row"> 
            <div class="column is-5 w-50">
                <%= form_for @category do |f| %>
                    <div class="form-group">
                        <%= f.label :title %>
                        <%= f.text_field :title , autofocus: true, autocomplete: "title", class: "form-control"%>
                    </div>

                    <div class="form-group">
                        <%= f.label :description ,"Description" %>
                        <%= f.text_field :description ,class:"form-control" %>
                    </div>
                    <br>
                    <div class="form-group">
                        <%= f.submit "Submit",class:"btn btn-block btn-success" %>
                    </div>
                <br>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<% provide(:title,'Admin|Categories') %>  
<br>  
<div class="container">
    <div class="column is-5 w-100">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-6">
                        <div>Admin|Categories</div>
                    </div>
                    <div class="col-sm-6 text-right">
                        <%= link_to 'Add category', new_category_path ,class:"btn btn-success "%>
                    </div>
                </div>
            </div>    
            <table class="table">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                        <tr>
                            <td ><%= link_to category.title, (category_words_list_url(category.id))  %></td>
                                <td><%= category.description %></td>
                                <td> <% if current_user.admin == true %> <%= link_to 'Add word', new_category_words_path(category.id), class:"btn btn-sm btn-info mr2"%> <%= link_to 'Edit',"edit_words_path(category.id)", class:"btn btn-sm btn-success mr2"%> <%= link_to 'delete', category_url(category) , method: :delete, data: {confirm: "You sure?"} %><% end %> </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>