config/routes.rb
Rails.application.routes.draw do
  get 'learn/new'
  get 'learn/show'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'static_pages#home'
  get '/dashboard',to: 'static_pages#index'
  
  get '/members',to: 'users#index'
  get '/profile' ,to: 'users#show'
  get '/signup',to: 'users#new'
  get '/setting', to: 'users#setting'

  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'
  
  resources :categories
  resources :words
  resources :learns , only: [:new, :create, :show]

  get '/categories/:category_id/words/new', to: 'words#new', :as => :new_category_words

  get '/categories/:category_id/words', to: 'words#index', :as => :category_words_list

  get '/categories/words', to: 'categories#show', :as => :category_words

  get '/categories/:category_id/words/:word_id/edit', to: 'words#edit', :as => :edit_category_words

  get '/categories/:category_id/words/', to: 'words#index', :as => :words_path
  
  resources :users do
    member do
       get :following, :followers
    end
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top bg-success text-white">
    <%= link_to "Flamgia", root_url ,class:"navbar-brand brand text-white" %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto text-white col-xs-12 col-lg-4">
        </ul>
        <ul class="navbar-nav pull-right text-white">
            <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to "Dashboard", dashboard_path, class:"nav-link text-white" %>
                </li>

                <% if current_user.admin == true %>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                        Admin user<b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <%= link_to "Categories",category_words_path , class: "dropdown-item" %>
                        </li>
                        <li>
                            <%= link_to "Add category", new_category_path, class: "dropdown-item" %>
                        </li>
                       
                    </ul>
                </li>
                <% end %>

                 <li class="nav-item">
                    <%= link_to "Categories", categories_path, class:"nav-link text-white" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Member", members_path, class:"nav-link text-white" %>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">
                        <%= current_user.name %><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <%= link_to "Profile", current_user, class: "dropdown-item" %>
                        </li>
                        <li>
                            <%= link_to "Settings",  edit_user_path(current_user), class: "dropdown-item" %>
                        </li>
                        <li>
                            <%= link_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
                        </li>
                    </ul>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "Signup", signup_path, class:"nav-link text-white" %>
                </li>
                <li class="nav-item ">
                    <%= link_to "Login", login_path, class:"nav-link text-white" %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
    <html>
        <head>
        <title><%= yield(:title) %>| E-learning</title>
        <title>ELearning</title>
           <%= csrf_meta_tags %>
           <%= csp_meta_tag %>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
            <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
            <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        </head>

        <body>
            <div class="container">
                <%= render 'layouts/header' %>
                <div class="mt-5">
                    <%= render 'shared/error_messages'%>
                </div>
                    <%= yield %>
            </div>  
                <footer class="text-center text-white bg-success" style="background-color: #f1f1f1;">
                    <div class="text-center text-white p-3" style="background-color: rgba(0, 0, 0, 0.2);">
                        © All right reserved
                    </div>
                </footer>   
        </body>
    </html>